apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
#clusterIP is a subtype of service
#ClusterIP is not accessible from the outside world
  type: ClusterIP
  selector:
    component: web
  ports:
  #port - how the other pod/cotainers communicate to this pod
    - port: 3050
    #targetPort  is the same as the container port in the pod yaml
    #redirect to a pod with port3000 
      targetPort: 3000
  selector:
    component: web