apiVersion: v1
#this is more of a billboard. PVC is attached to the pod
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec: 
#access Modes: 
  # ReadWriteOnce - can be used by a single node
  # ReadOnlyMany - multiple nodes can read from this
  # ReadWriteMany - can be read and written to by many nodes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    #kubernetes looks for a storage option that has 2 gigs of space
    #This space is taken from your compputer's harddrive on local
    # On a cloud provider, you have to specify what storage class to use
    # .eg. azure, awselasitcblockstorage, googlepersistentdisk
      storage: 2Gi
