apiVersion: v1
kind: Service
#metadata is how the worker will access this service
# this service will then talk to the pod based on the selector
metadata:
  name: redis-cluster-ip-service
spec:
#clusterIP is a subtype of service
#ClusterIP is not accessible from the outside world
  type: ClusterIP
  selector:
    component: redis
  ports:
  #port - how the other pod/cotainers communicate to this pod
    - port: 6379
    #targetPort  is the same as the container port in the pod yaml
    #redirect to a pod with port3000 
      targetPort: 6379
  selector:
    component: web