apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  #replica is the number of pods that this deployment is suppose to create
  replicas: 3
  selector:
  #which pod needs to be replicated? any pod with label `component:web`
    matchLabels:
      component: server
  template:
  #configuration of the pods that will be created
    metadata:
      labels:
        component: server
    spec:
      containers:
         #running container called client 
  # from dockerhub with image name kerv102/multi-client
  # containerPort - expose port 3000 to the outside world
        - name: server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000
          env:
          #REDIS HOST and the PG HOST are connection strings 
          # this is the name of the clusertervice
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
              #his port is the default value
            - name: PGPORT
              value: '5432'
              #we are just using the default db
            - name: PGDATABASE
              value: postgres
              # value for PGPASSWORD is from a configuration which is a secret
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
          

