apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  #replica is the number of pods that this deployment is suppose to create
  replicas: 1
  selector:
  #which pod needs to be replicated? any pod with label `component:web`
    matchLabels:
      component: worker
  template:
  #configuration of the pods that will be created
    metadata:
      labels:
        component: worker
    spec:
      containers:
         #name of the pod object
        - name: worker
          image: stephengrider/multi-worker
          #environment variables for logins eg. pw and username
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
